const jianXingEn = {
  settings: {
    microApps: {
      jianXing: {
        page: { miniTitle: "TouchRealm", title: "TouchRealm", description: "Connect to the current Chrome session to browse pages locally with TouchRealm or capture content with Clippings.", guide: "User guide" },
        guide: { close: "Close user guide", footerClose: "Close", title: "TouchRealm user guide", intro: "After the extension, Native, and authorization setup is complete, connection status syncs here automatically.", extensionTitle: "Install the TouchRealm extension", extensionBody: "Download, install, and enable TouchRealm from Chrome's extension manager. During development, load the project extension root, not its nested extension directory.", nativeTitle: "Register Native Messaging", nativeBody: "Click Install Native or Repair Native on this page. Native Installed only means Chrome can find the local connector; it does not mean the extension is online.", authTitle: "Authorize the extension", authBody: "Click Browser Extension Authorization to generate a one-time code, then paste it into the TouchRealm side panel in Chrome. The authorized extension connects to Native Messaging and Mira.", connectionTitle: "Confirm connection status", connectionBody: "Waiting for extension means Mira is ready and waiting for Chrome. TouchRealm and clipping-rule sync are available only after Extension connected appears.", usageTitle: "Use TouchRealm and Clippings", usageBody: "In TouchRealm, start with Look to read the page and element refs, then browse, click, fill, or transfer. Clippings is for user-initiated capture; site rules only affect content and image extraction for matching sites." },
        tabs: { jianxing: "TouchRealm", clipper: "Clippings" },
        modes: { look: "Look", browse: "Browse", act: "Act", transfer: "Transfer", lookDescription: "Read the current page state and stable element refs", browseDescription: "Open, go back, refresh, scroll, and wait", actDescription: "Click, fill, select, and press keys", transferDescription: "Upload files or retrieve downloads" },
        actions: { snapshot: "Page snapshot", page: "Page info", tabs: "Tab list", element: "Element details", screenshot: "Page screenshot", open: "Open URL in current tab", new: "Open new tab", switch: "Switch tab", close: "Close tab", back: "Back", forward: "Forward", reload: "Refresh", scroll: "Scroll", scrollTo: "Scroll to element", paginate: "Paginate", wait: "Wait", click: "Click", hover: "Hover", drag: "Drag", fill: "Fill", select: "Select", press: "Press", dialog: "Handle dialog", upload: "Upload file", download: "Get download" },
        connection: { chrome: "Chrome connection", extensionConnected: "Extension connected", waitingExtension: "Waiting for extension", disconnected: "Not connected", download: "Download extension", downloading: "Downloading…", authorize: "Browser extension authorization", disconnect: "Disconnect", connect: "Connect", supportedRegion: "Region picking supported", unsupportedRegion: "Region picking not reported", unknown: "Unknown", nativeInstall: "Install Native", nativeInstalling: "Installing…", nativeCheck: "Checking…", nativeUnavailable: "Native unavailable", nativeRepair: "Repair Native", nativeInstalled: "Native installed", nativeNeedsRepair: "Native needs repair", nativeNotInstalled: "Native not installed", unregister: "Unregister", local: "Local", extensionVersion: "Extension v{{version}}" },
        operation: { started: "Operating Chrome: {{operation}}", browserPage: "browser page", failed: "Operation failed", completed: "Completed", error: "Operation failed", status: "TouchRealm browser status" },
        fields: { parameters: "Parameters", parametersHint: "Read the page first, then use stable refs from the snapshot to act.", operation: "Operation", ref: "Element ref", refPlaceholder: "For example e17", file: "File", filePlaceholder: "Choose a file", url: "URL", scrollAmount: "Scroll distance (px)", waitTime: "Wait time (ms)", dragRefs: "From ref, to ref", downloadUrl: "Download URL", value: "Parameter value", valuePlaceholder: "Enter a value", sendViaNative: "Requests are sent through the local Native Messaging channel", authorizeFirst: "Authorize the TouchRealm extension in Chrome before sending requests", run: "Running…", observe: "Inspect page", send: "Send action", browserOnly: "TouchRealm browser status" },
        result: { title: "Page result", clear: "Clear", currentConnection: "Current connection", noResult: "No page result yet", localOnly: "Results are delivered only through the local connection", screenshot: "Page screenshot" },
        clipper: { title: "URL clipping rules", help: "Match complete URLs with wildcards or regular expressions; when multiple rules match, the most specific constraint wins.", refresh: "Refresh rules", refreshing: "Refreshing…", add: "Add rule", refreshFailed: "Rule refresh failed", status: "Rule status", empty: "No URL clipping rules" },
        auth: { title: "Browser extension authorization", close: "Close", intro: "Generate a one-time code and TouchRealm will open the authorization page. If Chrome does not switch to it, click the extension icon in the toolbar.", generate: "Generate code", generating: "Generating...", copy: "Copy", open: "Open authorization page", expiry: "The code is valid for 5 minutes and can be used once. Switch to the TouchRealm authorization page in Chrome, paste it, and click Authorize and connect. Mira connects automatically after authorization." },
        messages: { openAuthFailed: "Unable to open the TouchRealm authorization page. Reload the extension and try again.", nativeReadFailed: "Unable to read Native Messaging status", connectExtension: "Connect the TouchRealm extension first", rulesLoaded: "URL clipping rules loaded from the TouchRealm extension", rulesReadFailed: "Unable to read URL clipping rules", regionIncludePrompt: "Click the content region in Chrome", regionExcludePrompt: "Click the region to exclude in Chrome", regionIncluded: "Selected the content region on the current page", regionExcluded: "Added the exclusion region on the current page", regionFailed: "Region selection failed", urlRequired: "Enter a URL wildcard or regular expression", invalidRegex: "Invalid URL regular expression. Check parentheses, backslashes, and quantifiers.", rulesSaved: "URL clipping rules saved to the TouchRealm extension", rulesSaveFailed: "Unable to save URL clipping rules", ruleNotSaved: "This URL rule has not been saved", rulesDeleted: "URL clipping rule deleted", rulesDeleteFailed: "Unable to delete URL clipping rule", connectFailed: "Unable to connect to TouchRealm", browserFailed: "Browser operation failed", codeGenerated: "Authorization code generated. It is valid for 5 minutes and can be used once.", codeGenerateFailed: "Unable to generate authorization code", codeCopied: "Authorization code copied", extensionDownloaded: "Mira Clipper downloaded to the system Downloads folder", extensionDownloadFailed: "Extension download failed", nativeInstalled: "Native Messaging connector installed", nativeNeedsRepair: "Native Messaging still needs repair after installation", nativeInstallFailed: "Native Messaging installation failed", nativeUnregistered: "Native Messaging unregistered", nativeUnregisterFailed: "Native Messaging unregistration failed" },
        rules: { alias: "Alias", unnamed: "Unnamed", urlPattern: "URL match", regex: "Regex", wildcard: "Wildcard", content: "Content", selected: "Selected · {{tag}}", configured: "Region configured", defaultExtract: "Default extraction", images: "Images", imageCount: "{{count}}", enabled: "Enabled", disabled: "Disabled", status: "Status", actions: "Actions", edit: "Edit rule", editAria: "Edit {{name}} rule" },
        rulesDrawer: { close: "Close rule editor", editTitle: "Edit URL clipping rule", addTitle: "Add URL clipping rule", description: "Configure URL matching, page content, exclusion regions, and image extraction.", delete: "Delete rule", saving: "Saving…", save: "Save URL rule", syncFailed: "Rule sync failed", status: "Rule status", alias: "Site alias (optional)", aliasPlaceholder: "For example Help Center", urlPattern: "URL match rule", regexPlaceholder: "For example ^https://example\\.com/article/.*", wildcardPlaceholder: "For example https://example.com/article/*", matchMode: "Match mode", wildcard: "Wildcard", regex: "Regex", matchHelp: "Required. In wildcard mode, `*` matches any length of text and `?` matches one character. Regex mode accepts a JavaScript regular expression without flags. When multiple rules match, the extension uses the most specific constraint.", enabled: "Enable this rule", disabledHint: "When disabled, this URL range uses default extraction.", enabledAria: "Enable current URL rule", includeRegion: "Content region", picking: "Waiting for selection…", reselect: "Select again", selectInclude: "Select content region", noPreview: "The selected region has no previewable text.", legacyRegion: "This rule comes from an older configuration. Select the content region again to generate a readable summary.", emptyInclude: "Not selected. After saving, this site will still use the default content detection.", excludeRegion: "Exclusion regions", addExclude: "Add exclusion region", excludeItem: "Exclusion region {{index}} · {{tag}}", webRegion: "Web region", selectedRegion: "Web region selected", deleteExclude: "Delete exclusion region {{index}}", noExclude: "No exclusion regions", minWidth: "Minimum image width", minHeight: "Minimum image height", maxCount: "Image limit" },
      },
      studioEntries: { jianXing: { title: "TouchRealm", description: "Connect to the current Chrome session to inspect, browse, act on pages, and handle file operations locally.", actions: { open: "Open TouchRealm" } } },
    },
  },
} as const;

export default jianXingEn;
