/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{ts,tsx}",
    "./node_modules/streamdown/dist/**/*.js",
    "./node_modules/@streamdown/code/dist/**/*.js",
    "./node_modules/@streamdown/math/dist/**/*.js",
    "./node_modules/@streamdown/mermaid/dist/**/*.js",
  ],
  darkMode: "class",
  theme: {
    extend: {
      fontFamily: {
        sans: [
          '"IBM Plex Sans"',
          '"Noto Sans SC"',
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          '"Segoe UI"',
          "sans-serif",
        ],
        serif: [
          '"Source Han Serif CN"',
          '"Source Han Serif"',
          '"Noto Serif SC"',
          "ui-serif",
          "Georgia",
          "serif",
        ],
        mono: [
          '"Geist Mono"',
          "ui-monospace",
          "SFMono-Regular",
          '"SF Mono"',
          "Consolas",
          '"Liberation Mono"',
          "Menlo",
          "monospace",
        ],
      },
      colors: {
        primary: "rgb(var(--color-primary) / <alpha-value>)",
        "primary-hover": "rgb(var(--color-primary-hover) / <alpha-value>)",
        "primary-1": "rgb(var(--color-primary-1) / <alpha-value>)",
        "primary-2": "rgb(var(--color-primary-2) / <alpha-value>)",
        "primary-3": "rgb(var(--color-primary-3) / <alpha-value>)",
        "primary-4": "rgb(var(--color-primary-4) / <alpha-value>)",
        "primary-5": "rgb(var(--color-primary-5) / <alpha-value>)",
        "primary-6": "rgb(var(--color-primary-6) / <alpha-value>)",
        "primary-7": "rgb(var(--color-primary-7) / <alpha-value>)",
        "primary-8": "rgb(var(--color-primary-8) / <alpha-value>)",
        "primary-9": "rgb(var(--color-primary-9) / <alpha-value>)",
        cloudy: "rgb(var(--color-cloudy) / <alpha-value>)",
        "cloudy-1": "rgb(var(--color-cloudy-1) / <alpha-value>)",
        "cloudy-2": "rgb(var(--color-cloudy-2) / <alpha-value>)",
        "cloudy-3": "rgb(var(--color-cloudy-3) / <alpha-value>)",
        "cloudy-4": "rgb(var(--color-cloudy-4) / <alpha-value>)",
        "cloudy-5": "rgb(var(--color-cloudy-5) / <alpha-value>)",
        "cloudy-6": "rgb(var(--color-cloudy-6) / <alpha-value>)",
        "cloudy-7": "rgb(var(--color-cloudy-7) / <alpha-value>)",
        "cloudy-8": "rgb(var(--color-cloudy-8) / <alpha-value>)",
        "cloudy-9": "rgb(var(--color-cloudy-9) / <alpha-value>)",
        pampas: "rgb(var(--color-pampas) / <alpha-value>)",
        "pampas-1": "rgb(var(--color-pampas-1) / <alpha-value>)",
        "pampas-2": "rgb(var(--color-pampas-2) / <alpha-value>)",
        "pampas-3": "rgb(var(--color-pampas-3) / <alpha-value>)",
        "pampas-4": "rgb(var(--color-pampas-4) / <alpha-value>)",
        "pampas-5": "rgb(var(--color-pampas-5) / <alpha-value>)",
        "pampas-6": "rgb(var(--color-pampas-6) / <alpha-value>)",
        "pampas-7": "rgb(var(--color-pampas-7) / <alpha-value>)",
        "pampas-8": "rgb(var(--color-pampas-8) / <alpha-value>)",
        "pampas-9": "rgb(var(--color-pampas-9) / <alpha-value>)",
        secondary: "rgb(var(--color-secondary) / <alpha-value>)",
        success: "rgb(var(--color-success) / <alpha-value>)",
        "success-soft": "rgb(var(--color-success-soft) / <alpha-value>)",
        "success-border": "rgb(var(--color-success-border) / <alpha-value>)",
        "success-text": "rgb(var(--color-success-text) / <alpha-value>)",
        warning: "rgb(var(--color-warning) / <alpha-value>)",
        "warning-soft": "rgb(var(--color-warning-soft) / <alpha-value>)",
        "warning-border": "rgb(var(--color-warning-border) / <alpha-value>)",
        "warning-text": "rgb(var(--color-warning-text) / <alpha-value>)",
        danger: "rgb(var(--color-danger) / <alpha-value>)",
        "danger-soft": "rgb(var(--color-danger-soft) / <alpha-value>)",
        "danger-border": "rgb(var(--color-danger-border) / <alpha-value>)",
        "danger-text": "rgb(var(--color-danger-text) / <alpha-value>)",
        info: "rgb(var(--color-info) / <alpha-value>)",
        "info-soft": "rgb(var(--color-info-soft) / <alpha-value>)",
        "info-border": "rgb(var(--color-info-border) / <alpha-value>)",
        "info-text": "rgb(var(--color-info-text) / <alpha-value>)",
        surface: {
          primary: "rgb(var(--color-surface-primary) / <alpha-value>)",
          secondary: "rgb(var(--color-surface-secondary) / <alpha-value>)",
          tertiary: "rgb(var(--color-surface-tertiary) / <alpha-value>)",
          elevated: "rgb(var(--color-surface-elevated) / <alpha-value>)",
        },
        border: "rgb(var(--color-border) / <alpha-value>)",
        text: {
          primary: "rgb(var(--color-text-primary) / <alpha-value>)",
          secondary: "rgb(var(--color-text-secondary) / <alpha-value>)",
          tertiary: "rgb(var(--color-text-tertiary) / <alpha-value>)",
          inverted: "rgb(var(--color-text-inverted) / <alpha-value>)",
        },
        ink: "rgb(var(--color-ink) / <alpha-value>)",
        icon: {
          primary: "rgb(var(--color-icon-primary) / <alpha-value>)",
          secondary: "rgb(var(--color-icon-secondary) / <alpha-value>)",
          tertiary: "rgb(var(--color-icon-tertiary) / <alpha-value>)",
          inverted: "rgb(var(--color-icon-inverted) / <alpha-value>)",
        },
      },
      spacing: {
        "space-1": "4px",
        "space-2": "8px",
        "space-3": "12px",
        "space-4": "16px",
        "space-5": "20px",
        "space-6": "24px",
        "space-8": "32px",
        "space-10": "40px",
      },
      borderRadius: {
        "ui-control": "8px",
        "ui-surface": "10px",
        "ui-panel": "12px",
        "ui-overlay": "16px",
        "ui-hero": "20px",
        "radius-sm": "8px",
        "radius-md": "10px",
        "radius-lg": "14px",
        "radius-xl": "18px",
        pill: "9999px",
      },
      boxShadow: {
        "shadow-sm":
          "0 1px 2px rgba(15, 23, 42, 0.05), 0 1px 1px rgba(15, 23, 42, 0.03)",
        "shadow-md": "0 8px 24px rgba(15, 23, 42, 0.08)",
        "shadow-lg": "0 16px 40px rgba(15, 23, 42, 0.14)",
        "shadow-xl": "0 24px 60px rgba(15, 23, 42, 0.18)",
      },
      typography: {
        display: {
          fontSize: "28px",
          fontWeight: 600,
          lineHeight: "1.2",
        },
        "heading-1": {
          fontSize: "20px",
          fontWeight: 600,
          lineHeight: "1.3",
        },
        "heading-2": {
          fontSize: "16px",
          fontWeight: 600,
          lineHeight: "1.4",
        },
        body: {
          fontSize: "14px",
          fontWeight: 400,
          lineHeight: "1.6",
        },
        "body-small": {
          fontSize: "13px",
          fontWeight: 400,
          lineHeight: "1.5",
        },
        caption: {
          fontSize: "12px",
          fontWeight: 500,
          lineHeight: "1.4",
        },
      },
      transitionDuration: {
        "duration-150": "150ms",
        "duration-200": "200ms",
      },
    },
  },
  plugins: [],
};
